// Simple parrot chatbot implementation used by indexParrot.html
const chatbot = {
    name: "Parrot",
    // Copy the user input and alternate between lowercase and uppercase characters before ending with "!!!".
    reply: function (question) {
        let response = "";
        for (let i = 0; i < question.length; i++) {
            response += Math.random() < 0.5 ?
                question[i].toUpperCase() :
                question[i].toLowerCase();
        }
        return response + "!!!";
    }
};

// Get references to the input and output elements
const inputEl = document.getElementById("input");
const outputEl = document.getElementById("output");
const sendBtn = document.querySelector('.send-button');

// Automatically scroll to the bottom of the chatbot
const chatbotContainer = document.getElementById("chatbot-container");

// Add an event listener to the input element to listen for user input
inputEl.addEventListener("keydown", function (event) {
    // If the user presses the Enter key, get the user's input and generate a response
    if (event.key === "Enter") {
        sendMessage();
    }
});

// Add an event listener to the send button
sendBtn.addEventListener("click", function () {
    sendMessage();
});

function sendMessage() {
    // Enforce character limit in JS and remove surrounding whitespace
    const userInput = inputEl.value.trim().slice(0, 140);

    // If the user's input is empty, return without sending the message
    if (!userInput) {
        return;
    }

    // Clear the input element
    inputEl.value = "";

    // Instead of using innerHTML with user input, we use textContent
    const userMsg = document.createElement('p');
    const userLabel = document.createElement('strong');
    userLabel.className = 'blue-text';
    userLabel.textContent = 'You: ';

    userMsg.appendChild(userLabel);
    // This ensures any HTML tags typed by the user are rendered as plain text
    userMsg.appendChild(document.createTextNode(userInput));
    outputEl.appendChild(userMsg);

    // Create a specific element for the typing indicator
    const parrotMsg = document.createElement('p');
    parrotMsg.innerHTML = "<strong>Parrot:</strong> Parrot is typing...";
    outputEl.appendChild(parrotMsg);

    // Scroll to the bottom of the chatbot container
    chatbotContainer.scrollTop = chatbotContainer.scrollHeight;

    // Delay for 1 second before generating the chatbot's response
    setTimeout(() => {
        // Remove the specific typing indicator element safely
        if (parrotMsg.parentNode === outputEl) {
            outputEl.removeChild(parrotMsg);
        }

        // Generate a response from the chatbot
        const chatbotResponse = chatbot.reply(userInput);

        // Create the actual response element
        const responsePara = document.createElement('p');
        // innerHTML is safe here because 'chatbotResponse' is generated by code, not user input
        responsePara.innerHTML = `<strong>Parrot:</strong> ${chatbotResponse}`;
        outputEl.appendChild(responsePara);

        // Scroll to the bottom of the chatbot container
        chatbotContainer.scrollTop = chatbotContainer.scrollHeight;
    }, 1000);
}

// Open pop-up form
// Show the chat window and hide the open button
function openForm() {
    document.getElementById("chatbotForm").style.display = "block";
    document.querySelector(".open-button").style.display = "none";
}

// Close pop-up form
// Hide the chat window and show the open button
function closeForm() {
    document.getElementById("chatbotForm").style.display = "none";
    document.querySelector(".open-button").style.display = "block";
}

// close if Esc is pressed on the keyboard
document.addEventListener("keydown", function (event) {
    if (event.key === "Escape") {
        closeForm();
    }
});